<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PairOfEmployees.Application\PairOfEmployees.Application.csproj" />
    <ProjectReference Include="..\PairOfEmployees.Infrastructure\PairOfEmployees.Persistence.csproj" />
  </ItemGroup>

</Project>
